# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Caprock < Formula
  desc "Mission control for Claude Code — watch, control and orchestrate your sessions"
  homepage "https://caprock.dev"
  version "0.4.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dspv/caprock/releases/download/v0.4.1/caprock_0.4.1_darwin_amd64.tar.gz"
      sha256 "875c587f41b8fd16b9174e23dbf54fd734a2250a688129182e869985351e7f3c"

      define_method(:install) do
        bin.install "caprock"
        bin.install "caprock-hook"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dspv/caprock/releases/download/v0.4.1/caprock_0.4.1_darwin_arm64.tar.gz"
      sha256 "5c25e246fbd392c2f0448165986cc9a0bd754f08d19190139fd486a9de224e6c"

      define_method(:install) do
        bin.install "caprock"
        bin.install "caprock-hook"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dspv/caprock/releases/download/v0.4.1/caprock_0.4.1_linux_amd64.tar.gz"
      sha256 "f404dcd70f2a7db6dae433341bf8a33931ee485c2648ef36bcb8a7f12a8cf999"
      define_method(:install) do
        bin.install "caprock"
        bin.install "caprock-hook"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dspv/caprock/releases/download/v0.4.1/caprock_0.4.1_linux_arm64.tar.gz"
      sha256 "391b822553724db98b07571ab6457b00c142521979f0a7de13b6ed8378ef17f1"
      define_method(:install) do
        bin.install "caprock"
        bin.install "caprock-hook"
      end
    end
  end

  def caveats
    <<~EOS
      Start it with:  caprock up
      Then open:      http://127.0.0.1:4173
    EOS
  end
end
