# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Caprock < Formula
  desc "Mission control for Claude Code — watch, control and orchestrate your sessions"
  homepage "https://caprock.dev"
  version "0.4.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dspv/caprock/releases/download/v0.4.0/caprock_0.4.0_darwin_amd64.tar.gz"
      sha256 "9ad6773fa3fa8ebaee1a808e11f995a030ff7736274b51fc01a4f8125095fe4e"

      define_method(:install) do
        bin.install "caprock"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dspv/caprock/releases/download/v0.4.0/caprock_0.4.0_darwin_arm64.tar.gz"
      sha256 "be0c78f40e00bba581a25cca1d15fd164c870c32499727029956e759d5cc0386"

      define_method(:install) do
        bin.install "caprock"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dspv/caprock/releases/download/v0.4.0/caprock_0.4.0_linux_amd64.tar.gz"
      sha256 "9026f8b794c2d8a34f29b2637067c93d29929d9d413d62433624c65ab8a73233"
      define_method(:install) do
        bin.install "caprock"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dspv/caprock/releases/download/v0.4.0/caprock_0.4.0_linux_arm64.tar.gz"
      sha256 "d1f03f6467c66079b677bb45016267117267d82f920ff2cda1b1943eb3868558"
      define_method(:install) do
        bin.install "caprock"
      end
    end
  end

  def caveats
    <<~EOS
      Start it with:  caprock up
      Then open:      http://127.0.0.1:4173
    EOS
  end
end
