# This file was generated by GoReleaser. DO NOT EDIT.
cask "caprock" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "69e5dcd8ba9059fbd0b888e4b15401126647e14467fbf03e5ac7733dd902b08c"
      url "https://github.com/dspv/caprock/releases/download/v#{version}/caprock_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "5384d8fd6c62f54ab06fb8430f25b60d7e853813b09be5da8851a52ce691011d"
      url "https://github.com/dspv/caprock/releases/download/v#{version}/caprock_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "393181171d328a3140dcd4a0180e23dc6bf20878652f5cf9f3139f549d63ec10"
      url "https://github.com/dspv/caprock/releases/download/v#{version}/caprock_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "4a51a5bc942f703b2feda99dc3db23b5ff15da7d9d6da5eb09790073343d6c10"
      url "https://github.com/dspv/caprock/releases/download/v#{version}/caprock_#{version}_linux_arm64.tar.gz"
    end
  end

  name "caprock"
  desc "Mission control for Claude Code — watch, control and orchestrate your sessions"
  homepage "https://caprock.dev"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "caprock"

  # No zap stanza required

  caveats <<~EOS
    Start it with:  caprock up
    Then open:      http://127.0.0.1:4173
  EOS
end
