# This file was generated by GoReleaser. DO NOT EDIT.
cask "caprock" do
  version "0.3.0"

  on_macos do
    on_intel do
      sha256 "581dfa001100a9a77b88a54ae8377f5e8e4719058c907787c0a339a3a561a91e"
      url "https://github.com/dspv/caprock/releases/download/v#{version}/caprock_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "e2648c054ad3c2f5f120821b2f15e18cc8e35dc620bb637c61a21d197e75aab7"
      url "https://github.com/dspv/caprock/releases/download/v#{version}/caprock_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "ecb58b1627257f74b4f71bfe40ab7a27b6d8be67f128a1587f1e907109124ded"
      url "https://github.com/dspv/caprock/releases/download/v#{version}/caprock_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "56686fb92f5fc2a3ad39dade6bdb684ae297e9b50e5cee51ac48d59732379018"
      url "https://github.com/dspv/caprock/releases/download/v#{version}/caprock_#{version}_linux_arm64.tar.gz"
    end
  end

  name "caprock"
  desc "Mission control for Claude Code — watch, control and orchestrate your sessions"
  homepage "https://caprock.dev"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "caprock"

  # No zap stanza required

  caveats <<~EOS
    Start it with:  caprock up
    Then open:      http://127.0.0.1:4173
  EOS
end
