# This file was generated by GoReleaser. DO NOT EDIT.
cask "caprock" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "aefb722f0860574b6ee2cfe13c3f032e4108097dc94ed90eb6c943cfe7ba99e4"
      url "https://github.com/dspv/caprock/releases/download/v#{version}/caprock_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "7101c9403ab589a94d7096f351e4ce783687993661afa4b0dde5cebe3bfcff86"
      url "https://github.com/dspv/caprock/releases/download/v#{version}/caprock_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "e0a82392ae840553069d445562956c2a0ae19c3b2dad2518068a96c40bf16a18"
      url "https://github.com/dspv/caprock/releases/download/v#{version}/caprock_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "3967cc34e89b0b3268f4e2dfcdb16249ce0915708d138898b02231e61d91d988"
      url "https://github.com/dspv/caprock/releases/download/v#{version}/caprock_#{version}_linux_arm64.tar.gz"
    end
  end

  name "caprock"
  desc "Mission control for Claude Code — watch, control and orchestrate your sessions"
  homepage "https://caprock.dev"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "caprock"

  # No zap stanza required

  caveats <<~EOS
    Start it with:  caprock up
    Then open:      http://127.0.0.1:4173
  EOS
end
