# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Caprock < Formula
  desc "Mission control for Claude Code — watch, control and orchestrate your sessions"
  homepage "https://caprock.dev"
  version "0.77.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dspv/caprock/releases/download/v0.77.0/caprock_0.77.0_darwin_amd64.tar.gz"
      sha256 "0b382099b569792e9d4458d4a72699809fe597e749a0dbe81ffb956c3b24083d"

      define_method(:install) do
        bin.install "caprock"
        bin.install "caprock-hook"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dspv/caprock/releases/download/v0.77.0/caprock_0.77.0_darwin_arm64.tar.gz"
      sha256 "de708d82925decc95c34a93be093a4c6841ed6c2d10920985c62ac0a1d98ccd7"

      define_method(:install) do
        bin.install "caprock"
        bin.install "caprock-hook"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dspv/caprock/releases/download/v0.77.0/caprock_0.77.0_linux_amd64.tar.gz"
      sha256 "59c114605fa3f27aa3ff25432bd89384cb2e46c712270dac4e78f8b35ae9d914"
      define_method(:install) do
        bin.install "caprock"
        bin.install "caprock-hook"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dspv/caprock/releases/download/v0.77.0/caprock_0.77.0_linux_arm64.tar.gz"
      sha256 "0a40d9198ba33a28caedebd1cf473c7280f7d416c5ceae54c32013e0b28a672f"
      define_method(:install) do
        bin.install "caprock"
        bin.install "caprock-hook"
      end
    end
  end

  def caveats
    <<~EOS
      Start it with:  caprock up
      Then open:      http://127.0.0.1:22776
    EOS
  end
end
