# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Caprock < Formula
  desc "Mission control for Claude Code — watch, control and orchestrate your sessions"
  homepage "https://caprock.dev"
  version "0.82.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dspv/caprock/releases/download/v0.82.0/caprock_0.82.0_darwin_amd64.tar.gz"
      sha256 "14f09fb71856b28b88f2e9264c453cd28b9ff2b1af02f602d2e63f81326ad05c"

      define_method(:install) do
        bin.install "caprock"
        bin.install "caprock-hook"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dspv/caprock/releases/download/v0.82.0/caprock_0.82.0_darwin_arm64.tar.gz"
      sha256 "99dbbb1766bbc8791ea2e578648ee40345d39823a69604afb9517855565af561"

      define_method(:install) do
        bin.install "caprock"
        bin.install "caprock-hook"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dspv/caprock/releases/download/v0.82.0/caprock_0.82.0_linux_amd64.tar.gz"
      sha256 "ecf87066036dc8e1762b46e7234a8323cc7c441a2c1260974be91736a3a65a02"
      define_method(:install) do
        bin.install "caprock"
        bin.install "caprock-hook"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dspv/caprock/releases/download/v0.82.0/caprock_0.82.0_linux_arm64.tar.gz"
      sha256 "955e592af74b4f305ca526e1cd577bb3a8b8dd211e66d1d27cbbeaa4e3fd0e82"
      define_method(:install) do
        bin.install "caprock"
        bin.install "caprock-hook"
      end
    end
  end

  def caveats
    <<~EOS
      Start it with:  caprock up
      Then open:      http://127.0.0.1:22776
    EOS
  end
end
